### ISSUE TITLE
Delete Group Fails with ArgumentNullException

### ISSUE THREAD

**Issue by sandorfr** [geeklearningio/gl-dotnet-authorizations#40]
When trying to delete a group, it fails with:
```
System.ArgumentNullException occurred
 HResult=0x80004003
 Message=Value cannot be null.
 Source=Microsoft.EntityFrameworkCore
 StackTrace:
  at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
  at Microsoft.EntityFrameworkCore.DbContext.Remove[TEntity](TEntity entity)
  at GeekLearning.Authorizations.EntityFrameworkCore.AuthorizationsManager`1.<DeleteGroupAsync>d__16.MoveNext()
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Lucsan.Workbench.Service.Security.GroupService.<DeleteGroupAsync>d__10.MoveNext() in C:\Users\cyprien.autexier\Repos\Workbench\Backend\Lucsan.Workbench.Service\Security\GroupService.cs:line 101
```

I traced it back to [the removal of the group principal](https://github.com/geeklearningio/gl-dotnet-authorizations/blob/develop/src/GeekLearning.Authorizations.EntityFrameworkCore/AuthorizationsManager.cs#L323). But given the implementation of `GetEntityAsync` it's not fetched. 

It's not happening on the unit tests because the same DBContext is used to perform all operations. The unit test should probably be updated to be closer to real use cases.

The quick workaround if to fetch the group with the proper `Include(x=> x.Principal)` prior to calling DeleteGroup. There's different way to address that issue I think one is to actually add the capability to do includes as part of the GetEntityAsync with an extra argument.

**Comment by sandorfr** [comment]
I added the fix to the my group PR.
